analyzer:
  exclude:
    - "build/**"
    - "test/**.mocks.dart"
    - ".test_coverage.dart"
    - "coverage/**"
    - "assets/**"
    - "lib/src/common/localization/generated/**"
    - "lib/src/common/constants/pubspec.yaml.g.dart"
    - "lib/src/common/model/generated/**"
    - "**.g.dart"
    - "**.gql.dart"
    - "**.freezed.dart"
    - "**.config.dart"
    - "**.mocks.dart"
    - "**.gen.dart"
    - "**.pb.dart"
    - "**.pbenum.dart"
    - "**.pbjson.dart"
    - ".fvm/**"
    - "scripts/**"
    - ".dart_tool/**"
    - "ios/**"
    - "android/**"
    - "web/**"
    - "macos/**"
    - "windows/**"
    - "linux/**"

  language:
    strict-casts: true
    strict-raw-types: true
    strict-inference: true

  errors:
    todo: ignore
    directives_ordering: info
    always_declare_return_types: warning
    unsafe_html: warning
    missing_return: warning
    missing_required_param: warning
    no_logic_in_create_state: warning
    empty_catches: warning

    # Error-level (toza import siyosati)
    always_use_package_imports: error
    avoid_relative_lib_imports: error
    avoid_slow_async_io: error
    avoid_types_as_parameter_names: error
    valid_regexps: error

    # Deprecated yoki jamoada xohishga ko'ra
    always_require_non_null_named_parameters: ignore
    avoid_positional_boolean_parameters: ignore

linter:
  rules:
    # Import siyosati (relative emas)
    prefer_relative_imports: false
    avoid_relative_lib_imports: true
    always_use_package_imports: true

    # Foydali amaliy qoidalar
    unnecessary_async: true
    avoid_slow_async_io: true
    strict_top_level_inference: true
    use_named_constants: true
    unnecessary_constructor_name: true
    sort_constructors_first: true
    exhaustive_cases: true
    sort_unnamed_constructors_first: true
    type_literal_in_constant_pattern: true
    always_put_required_named_parameters_first: true
    avoid_annotating_with_dynamic: true
    avoid_bool_literals_in_conditional_expressions: true
    avoid_field_initializers_in_const_classes: true
    avoid_implementing_value_types: true
    avoid_js_rounded_ints: true
    avoid_print: true
    avoid_renaming_method_parameters: true
    avoid_returning_null_for_void: true
    avoid_single_cascade_in_expression_statements: true
    avoid_unnecessary_containers: true
    avoid_unused_constructor_parameters: true
    avoid_void_async: true
    await_only_futures: true
    cancel_subscriptions: true
    cascade_invocations: true
    close_sinks: true
    control_flow_in_finally: true
    empty_statements: true
    collection_methods_unrelated_type: true
    join_return_with_assignment: true
    leading_newlines_in_multiline_strings: true
    literal_only_boolean_expressions: true
    missing_whitespace_between_adjacent_strings: true
    no_adjacent_strings_in_list: true
    no_logic_in_create_state: true
    only_throw_errors: true
    overridden_fields: true
    package_names: true
    package_prefixed_library_names: true
    parameter_assignments: true
    prefer_asserts_in_initializer_lists: true
    prefer_asserts_with_message: true
    prefer_const_constructors: true
    prefer_const_constructors_in_immutables: true
    prefer_const_declarations: true
    prefer_const_literals_to_create_immutables: true
    prefer_constructors_over_static_methods: true
    prefer_expression_function_bodies: true
    prefer_final_in_for_each: true
    prefer_foreach: true
    prefer_if_elements_to_conditional_expressions: true
    prefer_inlined_adds: true
    prefer_int_literals: true
    prefer_is_not_operator: true
    prefer_null_aware_operators: true
    prefer_typing_uninitialized_variables: true
    prefer_void_to_null: true
    provide_deprecation_message: true
    sized_box_for_whitespace: true
    sort_child_properties_last: true
    test_types_in_equals: true
    throw_in_finally: true
    unnecessary_null_aware_assignments: true
    unnecessary_overrides: true
    unnecessary_parenthesis: true
    unnecessary_raw_strings: true
    unnecessary_statements: true
    unnecessary_string_escapes: true
    unnecessary_string_interpolations: true
    use_full_hex_values_for_flutter_colors: true
    use_raw_strings: true
    use_string_buffers: true
    valid_regexps: true
    void_checks: true

    # Eski pedantic ro'yxatini kiritmang; zarur bo'lsa alohida qoida qo'shing.
